services:
  - type: web
    name: aws-quiz-backend
    runtime: python
    rootDir: backend
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://aws-quiz-nu.vercel.app
